/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal development and kept here so the
// project is ready to open in editors before dependencies are installed.
